#!/bin/bash
# DeepTools Tornado Plot Analysis
# Generated by Shiny App

# Set script to exit on error
set -e

# Load required modules
ml deeptools

# Define variables
PROJECT_ID="my-test"
OUT_DIR="/blue/cancercenter-dept/hkates/Apps/torando-plotter/output/my-test"
MATRIX_FILE="$OUT_DIR/my-test_matrix.gz"
HEATMAP_FILE="$OUT_DIR/my-test_heatmap.png"
LOG_DIR="$OUT_DIR/LOGS"
REGIONS_FILE="/blue/cancercenter-dept/hkates/Projects_2025_Feb-May/Clanton/Male/OUTPUT/genome/genes.tss.bed"
SORTED_BED="$OUT_DIR/my-test_sorted.bed"

# BigWig files array
BIGWIG_FILES=("/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Control_REP1.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Control_REP2.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Control_REP3.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Heat_REP1.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Heat_REP2.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Heat_REP3.mLb.clN.bigWig" "/blue/cancercenter-dept/privapps/data/atac/clanton/NS4167_Male_GoodSamples/Heat_REP4.mLb.clN.bigWig")

# Create necessary directories
mkdir -p "$OUT_DIR" "$LOG_DIR"

echo "Starting DeepTools analysis for project: $PROJECT_ID"
echo "Output directory: $OUT_DIR"
echo "Regions file: $REGIONS_FILE"
echo "BigWig files: ${BIGWIG_FILES[@]}"

# Run computeMatrix
echo "Running computeMatrix..."
computeMatrix reference-point \
    --referencePoint TSS \
    -b 2000 -a 2000 \
    -R "$REGIONS_FILE" \
    -S "${BIGWIG_FILES[@]}" \
    --skipZeros \
    --missingDataAsZero \
    -p 4 \
    -o "$MATRIX_FILE" \
    2>&1 | tee "$LOG_DIR/computeMatrix.log"

# Wait for computeMatrix to complete
wait

echo "computeMatrix completed successfully"

# Run plotHeatmap
echo "Running plotHeatmap..."
plotHeatmap \
    -m "$MATRIX_FILE" \
    -o "$HEATMAP_FILE" \
    --heatmapWidth 6 \
    --samplesLabel "Control_REP1" "Control_REP2" "Control_REP3" "Heat_REP1" "Heat_REP2" "Heat_REP3" "Heat_REP4" \
    --xAxisLabel "distance (bp)" \
    --refPointLabel "TSS" \
    --yAxisLabel "Genes" \
    --regionsLabel "ATAC" \
    --colorList "white,red" \
    --sortUsing mean \
    --outFileSortedRegions "$SORTED_BED"

echo "plotHeatmap completed successfully"

# Summary
echo "=================================================="
echo "Analysis complete! Files saved in: $OUT_DIR"
echo "Heatmap: $HEATMAP_FILE"
echo "Matrix: $MATRIX_FILE"
echo "Sorted regions: $SORTED_BED"
echo "Logs: $LOG_DIR"
echo "=================================================="

# Check file sizes
echo "Output file sizes:"
ls -lh "$HEATMAP_FILE" "$MATRIX_FILE" "$SORTED_BED" 2>/dev/null || echo "Some output files not found"

echo "DeepTools tornado plot analysis completed for $PROJECT_ID"
