#!/bin/bash
# DeepTools Tornado Plot Analysis
# Generated by Shiny App

# Set script to exit on error
set -e

# Load required modules
ml deeptools

# Define variables
PROJECT_ID="{{PROJECT_ID}}"
OUT_DIR="{{OUTPUT_DIR}}/{{PROJECT_ID}}"
MATRIX_FILE="$OUT_DIR/{{PROJECT_ID}}_matrix.gz"
HEATMAP_FILE="$OUT_DIR/{{PROJECT_ID}}_heatmap.png"
LOG_DIR="$OUT_DIR/LOGS"
REGIONS_FILE="{{REGIONS_FILE}}"
SORTED_BED="$OUT_DIR/{{PROJECT_ID}}_sorted.bed"

# BigWig files array
BIGWIG_FILES=({{BIGWIG_FILES}})

# Create necessary directories
mkdir -p "$OUT_DIR" "$LOG_DIR"

echo "Starting DeepTools analysis for project: $PROJECT_ID"
echo "Output directory: $OUT_DIR"
echo "Regions file: $REGIONS_FILE"
echo "BigWig files: ${BIGWIG_FILES[@]}"

# Run computeMatrix
echo "Running computeMatrix..."
computeMatrix reference-point \
    --referencePoint {{REFERENCE_POINT}} \
    -b {{BEFORE_REGION}} -a {{AFTER_REGION}} \
    -R "$REGIONS_FILE" \
    -S "${BIGWIG_FILES[@]}" \
    {{SKIP_ZEROS}} \
    {{MISSING_DATA_AS_ZERO}} \
    -p {{PROCESSORS}} \
    -o "$MATRIX_FILE" \
    2>&1 | tee "$LOG_DIR/computeMatrix.log"

# Wait for computeMatrix to complete
wait

echo "computeMatrix completed successfully"

# Run plotHeatmap
echo "Running plotHeatmap..."
plotHeatmap \
    -m "$MATRIX_FILE" \
    -o "$HEATMAP_FILE" \
    --heatmapWidth {{HEATMAP_WIDTH}} \
    --samplesLabel "{{SAMPLE_LABELS}}" \
    --xAxisLabel "{{X_AXIS_LABEL}}" \
    --refPointLabel "{{REFERENCE_POINT}}" \
    --yAxisLabel "{{Y_AXIS_LABEL}}" \
    --regionsLabel "{{REGIONS_LABEL}}" \
    --colorList "{{COLOR_LIST}}" \
    --sortUsing {{SORT_USING}} \
    --outFileSortedRegions "$SORTED_BED"

echo "plotHeatmap completed successfully"

# Summary
echo "=================================================="
echo "Analysis complete! Files saved in: $OUT_DIR"
echo "Heatmap: $HEATMAP_FILE"
echo "Matrix: $MATRIX_FILE"
echo "Sorted regions: $SORTED_BED"
echo "Logs: $LOG_DIR"
echo "=================================================="

# Check file sizes
echo "Output file sizes:"
ls -lh "$HEATMAP_FILE" "$MATRIX_FILE" "$SORTED_BED" 2>/dev/null || echo "Some output files not found"

echo "DeepTools tornado plot analysis completed for $PROJECT_ID"
